### PR TITLE
Correct imprecise regex in moveModuleUp function (fixes #444)

### LINKED ISSUE #444: Python files from unrelated modules present when using package: individually
I'm expecting my final module's zip file to include something like:
```
package_name/app.py
package_name/file.py
tests/test_package_name.py
.flake8
.pylintrc
...
```

but I'm also seeing files from unrelated modules:

```
SomeUnrelatedModule/is_showing_up/app.py
OtherUnrelatedModule/something_saas_function/app.py
package_name/app.py
package_name/file.py
tests/test_package_name.py
.flake8
.pylintrc
...
```

The regex in this filter expression appears to be too general:
https://github.com/UnitedIncome/serverless-python-requirements/blob/master/lib/inject.js#L70

I'm getting files from unrelated modules which match this regex, e.g.
`OtherModule/some_cool_function_is_matching/the_regex.py`

I don't fully understand the purpose of that regex in the filter, but my assumption is that rather than `s_.*\.py` it should be `^s_.*\.py`.

If this is the case let me know and I can raise a PR to correct the regex.

### PR DESCRIPTION
**Pull request by jimpudar**
The existing regex had the side effect of matching python files
from other modules if their filename or path happened to contain
the string `s_`.

### CODE REVIEW

**Comment by jimpudar** [comment]
@dschep any comments on this PR? Based on our conversation in #444 it seems to me this should be good to merge.

**Comment by dschep** [comment]
@alexdebrie can you confirm this will work fine with sls pro?

**Comment by jimpudar** [comment]
@alexdebrie any comments on this?

**Comment by dschep** [comment]
welp, he doesn't work at serverless any more either.. @astuyve are there any pythonistas left? :grimacing:

**Comment by astuyve** [comment]
I'm always game to learn, could we write a bit more about how to reproduce this bug? I'm happy to give it a shot and let you know

**Comment by dschep** [comment]
If i'm not mistaken, it's taht it would include a file like `foos_ball.py` when otherwise the include/exclude rules would have excluded it. Mostly wanting to make sure this change doesn't break sls pro.

**Comment by jimpudar** [comment]
@astuyve, here is a minimal example to show the issue.

Directory structure looks like this:

```
.
├── package-lock.json
├── package.json
├── package1
│   └── handler.py
├── package2_matches_regex
│   └── handler.py
└── serverless.yml
```

The `serverless.yml` file:

```
service: bug444

provider:
  name: aws
  runtime: python3.8

package:
  individually: true

functions:
  hello1:
    module: package1
    handler: handler.hello
  hello2:
    module: package2_matches_regex
    handler: handler.hello

plugins:
  - serverless-python-requirements
```

After running `sls package` and examining the zipped files in `.serverless`, we can see that the `package1-bug444-dev-hello1` zip file contains the spurious `package2_matches_regex` directory.

```
package1-bug444-dev-hello1
├── handler.py
└── package2_matches_regex
    └── handler.py

package2_matches_regex-bug444-dev-hello2
└── handler.py
```

Hopefully it's clear why this is undesirable, let me know if you need any further elaboration.

**Pull request merged**
