### PR TITLE
Fix single function deployment

### PR DESCRIPTION
**Pull request by lephuongbg**
This will fix https://github.com/serverless/serverless/issues/6752 and https://github.com/UnitedIncome/serverless-python-requirements/issues/414

### CODE REVIEW

**Comment by lephuongbg** [comment]
There is also this PR that also attempts to fix the same issue: https://github.com/UnitedIncome/serverless-python-requirements/pull/428. 

What that PR does is trying to guess the `artifactPath`, which I feel a bit more fragile and also more code needed than this PR's approach.

**Comment by mirstan** [comment]
hi, is this going to be merged?

**Comment by GCO-NZ** [comment]
Is this still being worked on?

**Comment by lephuongbg** [comment]
@GCO-NZ Just waiting for it to be merged only.

**Comment by mirstan** [comment]
@jacksgt can you merge this or does @lephuongbg need to update the PR? Thanks

**Comment by jacksgt** [comment]
@mirstan I don't have any permissions on this repo.

**Comment by jimpudar** [comment]
This is pretty huge functionality for anybody working on projects with a lot of functions. My entire project takes upwards of 45 minutes to deploy, but a single function deployment only takes around 30s.

We should really get merging this prioritized!

I have been using this as a local patch for months now with no issues. If there's anything else I can do to speed up the merge please let me know!

**Comment by Aubtin** [comment]
@bsamuel-ui @AndrewFarley @miketheman 

Can this be merged?

**Comment by bsamuel-ui** [comment]
Agreed on prioritizing this.

**Comment by bsamuel-ui** [comment]
@lephuongbg can you add a dummy commit to trigger CI?

**Comment by lephuongbg** [comment]
@bsamuel-ui  I've rebased this branch on master.

**Comment by lephuongbg** [comment]
@bsamuel-ui Just did but what was supposed to happen?

**Comment by bsamuel-ui** [comment]
> Just did but what was supposed to happen?

@lephuongbg All the CI ran... and we've got some tests failing.

**Comment by bsamuel-ui** [comment]
Please refer to #550

**Pull request merged**
