### PR TITLE
Change to poetry command to export requirements.txt resolving #445

### PR DESCRIPTION
**Pull request by JoeyC1990**
Hi, Here is the first attempt at fixing the change in the poetry export command.

The change needed was detailed here: [https://python-poetry.org/docs/cli/#export](url)

### CODE REVIEW

**Comment by JoeyC1990** [comment]
I have now made this change so hopefully this is ready to be merged

**Comment by jimpudar** [comment]
I would also love for this to be merged. Currently relying on a workaround for this issue.

**Comment by jimpudar** [comment]
There's also a corresponding change in the README which needs to be made that references this change.

https://github.com/UnitedIncome/serverless-python-requirements/blob/master/README.md#poetry-support-sparklespencilsparkles

Also, bump - this is a pretty huge issue that prevents anyone using Poetry with this plugin!

**Comment by JoeyC1990** [comment]
I have updated the readme so this is now ready to push @dschep please can this be merged?

**Comment by wozniakty** [comment]
Yeah, this is completely blocking my current project from using poetry :(

**Comment by miketheman** [comment]
This change to require the use of `-o` flag has broken CI, as the `-o` flag was not present in `poetry` version 1.0.0a0 - and a specific test was added in #395 to enable testing against the older version, which has since been overridden here.

There's a few paths forward that I can think of:

1. Reverse the approach taken here and revert to using `stdout` and redirection.
1. Add poetry version detection logic and try to use redirection if detected.
1. Remove the test for pre-release poetry version, and commit to the stability of version 1.0.0 which supports the `-o` flag.

I'm leaning towards the final one - this is likely the last bit before we can have a full CI pass again - I've been working through that on #462

**Comment by bsamuel-ui** [comment]
I agree with dropping support for prerelease poetry.

**Pull request merged**
