### PR TITLE
Prevent serverless package hash from changing

### PR DESCRIPTION
**Pull request by mokamoto12**
Modify the following to prevent modification of the serverless deploy package file hash.

+ Inserting packages asynchronously changes the order
+ The timestamp is changed when creating a folder in the package zip file with `jszip`

Changing the file hash will cause unnecessary deployment.

I'm sorry my English is not good.

### CODE REVIEW

**Comment by dschep** [comment]
Makes sense. looks good to me!

**Comment by dschep** [comment]
seems like tests fail tho.

**Comment by mokamoto12** [comment]
Thank you for your approval!
I think circleci's test failure is caused by #395, I try to fix it.
Sorry, I'm not familiar with appveyor. I don't know the cause.

**Comment by dschep** [comment]
>  I think circleci's test failure is caused by #395, I try to fix it.

ah. i see.
>  Sorry, I'm not familiar with appveyor. I don't know the cause. 

dont worry about it

**Comment by mokamoto12** [comment]
Test failure is fixed. I am sorry to trouble you, but could you add a job for the circle?
I'm looking forward to this release!

**Comment by dschep** [comment]
yup! hopefully we'll be moving to github actions soon anyway 😁

**Pull request merged**
