### PR TITLE
 First pass at tape tests instead of bats tests

### LINKED ISSUE #249: Add proper windows CI test coverage
as #247 and #248 make obvious, testing on windows machines is not part of the usual release flow. This should change, but I'm not sure how to best go about running the bats test suite on windows or if it should be ported(not preferable, since then you have to maintain multiple test suites)

Also, it would be of interest to run this the various ways you can run it on windows (now of course, some of these make it much easier to use bats, eg when using WSL):
 * vanilla windows + docker for windows
 * vanilla windows + docker toolbox
 * WSL + "wsl" docker
 * WSL + docker for windows
 * cygwin + docker for windows
 * more? less? windows is so complicated.

CCing those I know to be windows-based users&contributors: @kichik @heri16 @vecchp @hubbins @ajshukury @lucasnp (others? If you know, plz tag them)

### PR DESCRIPTION
**Pull request by dschep**
Main advantage is that these can run on windows more easily, thus fixes #249 

cc @AndrewFarley @kichik @heri16

### CODE REVIEW

**Comment by AndrewFarley** [comment]
This is great @dschep thanks for bootstrapping this.  If you want a hand with something in particular or a second eye let me know.  Happy to help.  Cheers!

**Comment by dschep** [comment]
Thanks @AndrewFarley. I currently need help debugging the errors with npm not being found by `spawnSync` in appveyor, if someone with Windows could try to run the tests locally (clone this branch, then: `npm i && node test.js`) that would be much appreciated. For further help, I'm gonna first get the skip conditions worked out (ie: when not to run the docker tests) and then I'll probably want some help just porting over the remaining tests.

**Comment by dschep** [comment]
woo hooo. tests passing. temporarily cherrypicked a "fix" for #252 to make it happen

**Comment by dschep** [comment]
Merging this now as it's already way better than the current(broken) windows test coverage.

**Pull request merged**
