### PR TITLE
Preserve binary file permissions in zip

### PR DESCRIPTION
**Pull request by bspink**
Fixes https://github.com/UnitedIncome/serverless-python-requirements/issues/233

### CODE REVIEW

**Comment by dschep** [comment]
Hmm, do tests pass for you locally?

**Comment by bspink** [comment]
@dschep they were passing locally for me, *but* I was running a hacked-up version of the circleci yaml file to run circleci locally using docker containers and most tests were passing (including the 3 new ones added here).

Once it ran on the machine executor I had an issue with an older version of `pip` (fixed in the PR already). Will fix the issue with the last failing test today. 👍

**Comment by bspink** [comment]
@dschep OK, fixed the tests - I was relying on hardcoded permissions values, but now grab them from the appropriate files dynamically.

**Comment by davidtsuji** [comment]
Nice work! This fixes an issue I'm seeing. When might this be published to npm?

**Pull request merged**
