### PR TITLE
Support poetry private repos

### PR DESCRIPTION
**Pull request by ofercaspi**

### CODE REVIEW

**Comment by ofercaspi** [comment]
This PR resolves [Issue 407](https://github.com/UnitedIncome/serverless-python-requirements/issues/407)

**Comment by bsamuel-ui** [comment]
Please see #550

**Review by bsamuel-ui — APPROVED** [review]
LGTM.

**Comment by ofercaspi** [comment]
Thanks!
Do we know when is the next release expected?

**Pull request merged**
