### PR TITLE
Fix issue 274

### PR DESCRIPTION
**Pull request by T-Tmnr**
Fix issues on Windows platform using Docker.
- Appended windowsVerbatimArguments option to `spawnSync` on docker.js
- Fix bindPath to enclose by double-quart on docker.js.
- When dockerizePip is enabled and Win32 platform, switch pythonBin from `python.exe` to `python`.

### CODE REVIEW

**Comment by dschep** [comment]
@adanot and @gbrcmg does this fix work for you too? Install with:
```
npm i -g T-Tmnr/serverless-python-requirements#fix-issue-274
```

@heri16 @kichik, does this look good?

**Comment by kichik** [comment]
I'm not sure how that would work based on this comment:

https://github.com/UnitedIncome/serverless-python-requirements/issues/274#issuecomment-438654122

With quotes on `bindPath` itself it will produce commands with:

```
-v something:"something with space"
```

But the comment suggests (and it seems logically correct) this is required:

```
-v "something:something with space"
```

**Comment by dschep** [comment]
@kichik, does the inclusion of `windowsVerbatimArguments` not affect this choice?

**Comment by kichik** [comment]
I think it just tells it not to convert `-v test:"hello world"` to `-v "test:"hello world""`.

**Comment by T-Tmnr** [comment]
I modified code using modification on v4.2.5 fully.

@kichik `-v "something:something with space"` is also correct.
I try to fix the issue by this pattern on my another branch.
https://github.com/T-Tmnr/serverless-python-requirements/tree/fix-issue-274-another
But it's revert changes at `dockerPathForWin` of v4.2.5.

windowsVerbatimArguments option tells 'not quoating cmdOptions on windows platform'.
In this case `cmdOptions=['-v', 'test:"hello world"']` without windowsVerbatimArguments,
quating 'test:"hello world"' to '"test:\"hello world\""'.
Finally, the spawned command got arguments bellow.
```
$1=-v 
$2="test:\"hello 
$3=world\"" 
```

**Comment by T-Tmnr** [comment]
I posted to the issue.
https://github.com/UnitedIncome/serverless-python-requirements/issues/274#issuecomment-439486764

**Comment by kichik** [comment]
My two cents on this:

1. `-v "something:something with spaces"` is more correct than `-v something:"something with space"` and doesn't rely on any special treatment of quotes.
1. It will be easier in the future if we separate quote handling from command generation. We might have more code paths that we're missing here or that will be added. I personally prefer letting the code doing the actual execution deal with the quoting. In this case it would be `spawnSync()` without `windowsVerbatimArguments`. If it doesn't know how to properly quote, let's create a wrapper for it that does. But handling the quotes in the code that builds the command will mean that has to be done in any code that calls a command.

**Comment by bsamuel-ui** [comment]
> It will be easier in the future if we separate quote handling from command generation.

I'm doing exactly that in #292.

**Pull request closed without merging**
