### PR TITLE
Suggest excluding cache folder

### PR DESCRIPTION
**Pull request by kichik**

### CODE REVIEW

**Comment by dschep** [comment]
Any reason to suggest it instead of simply making it so? Meaning, have the plugin add that to the excludes, like how it used to add all the deps to the includes(before your changes in #147 of course)

**Comment by kichik** [comment]
That would require parsing `pipCmdExtraArgs`. It's possible, but I think if we're going that route a simpler `pipCache: true` option would be even better. We should even turn it on by default.

**Comment by dschep** [comment]
I like that idea. If we can have caching by default, that's optimal IMO. I'd prefer it to go in `.serverless/pip-cache` just to keep cruft contained. And infact, that would remove the need for omitting it from packaging, since `.serverless` is never packaged.

**Comment by kichik** [comment]
The problem with `.serverless` is that it often gets wiped. Also, we should probably limit this only to Docker builds. Otherwise we risk ignoring the pre-existing system cache.

In the future we can also figure out a good way to automatically mount the system cache, if it exists.

**Comment by dschep** [comment]
Good point. Merging this for now then :+1:

**Pull request merged**
