### PR TITLE
Port tests from bats to tape

### PR DESCRIPTION
**Pull request by bweigel**
hi @dschep 

I decided to split up and simplify PR #279 a little bit.
Started with porting some tests, which also helps towards resolutions of #269 ...

### CODE REVIEW

**Comment by bweigel** [comment]
At least one test using the `downloadCache` option fails on Windows. However, this seems to be a runtime error during `pip install ...`:

```
Could not install packages due to an EnvironmentError: [Error 123] The filename, directory name, or volume label syntax is incorrect:
 'C\\:\\\\Users\\\\appveyor\\\\AppData\\\\Local\\\\UnitedIncome\\\\serverless-python-requirements\\\\Cache\\\\downloadCacheslspyc\\wheels\\76\\a0\\b4\\2a3ee1a32d0506931e558530258de1cc04b628eff1b2f008e0\\*.*'
```

 Any ideas @AndrewFarley @dschep ?

<details>
<summary><b>Test output...</b></summary>

```bash
# py3.6 uses download cache with useDownloadCache option
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command requirements
Serverless: Load command requirements:clean
Serverless: Load command requirements:install
Serverless: Load command requirements:cleanCache
Serverless: Invoke package
Serverless: Invoke aws:common:validate
Serverless: Invoke aws:common:cleanupTempDir
Serverless: Generated requirements from C:\projects\serverless-python-requirements\tests\base\requirements.txt in C:\projects\serverless-python-requirements\tests\base\.serverless\requirements.txt...
Serverless: Installing requirements from C:\projects\serverless-python-requirements\tests\base\.serverless\requirements\requirements.txt ...
Serverless: Using download cache directory C:\Users\appveyor\AppData\Local\UnitedIncome\serverless-python-requirements\Cache\downloadCacheslspyc
Collecting bottle (from -r C:/projects/serverless-python-requirements/tests/base/.serverless/requirements/requirements.txt (line 1))
 
  Error --------------------------------------------------
 
  null
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
Error: null
    at installRequirements (C:\projects\serverless-python-requirements\tests\base\node_modules\serverless-python-requirements\lib\pip.js:269:11)
    at installRequirementsIfNeeded (C:\projects\serverless-python-requirements\tests\base\node_modules\serverless-python-requirements\lib\pip.js:458:3)
    at ServerlessPythonRequirements.installAllRequirements (C:\projects\serverless-python-requirements\tests\base\node_modules\serverless-python-requirements\lib\pip.js:537:29)
From previous event:
    at PluginManager.invoke (C:\Users\appveyor\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:391:22)
    at PluginManager.run (C:\Users\appveyor\AppData\Roaming\npm\node_modules\serverless\lib\classes\PluginManager.js:422:17)
    at variables.populateService.then.then (C:\Users\appveyor\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:157:33)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Serverless.run (C:\Users\appveyor\AppData\Roaming\npm\node_modules\serverless\lib\Serverless.js:144:8)
    at serverless.init.then (C:\Users\appveyor\AppData\Roaming\npm\node_modules\serverless\bin\serverless:44:28)
    at <anonymous>
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           8.12.0
     Serverless Version:     1.33.1
 
Could not install packages due to an EnvironmentError: [Error 123] The filename, directory name, or volume label syntax is incorrect: 'C\\:\\\\Users\\\\appveyor\\\\AppData\\\\Local\\\\UnitedIncome\\\\serverless-python-requirements\\\\Cache\\\\downloadCacheslspyc\\wheels\\76\\a0\\b4\\2a3ee1a32d0506931e558530258de1cc04b628eff1b2f008e0\\*.*'
C:\projects\serverless-python-requirements\test.js:38
    throw new Error(`${cmd} failed with status code ${status}`);
    ^
Error: sls failed with status code 1
    at C:\projects\serverless-python-requirements\test.js:38:11
    at t (C:\projects\serverless-python-requirements\test.js:672:3)
    at Test.tape.test.t (C:\projects\serverless-python-requirements\test.js:76:7)
    at Test.bound [as _cb] (C:\projects\serverless-python-requirements\node_modules\tape\lib\test.js:76:32)
    at Test.run (C:\projects\serverless-python-requirements\node_modules\tape\lib\test.js:95:10)
    at Test.bound [as run] (C:\projects\serverless-python-requirements\node_modules\tape\lib\test.js:76:32)
    at Immediate.next [as _onImmediate] (C:\projects\serverless-python-requirements\node_modules\tape\lib\results.js:71:15)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
```

</details>

**Comment by dschep** [comment]
Dude. HUUGGE thanks for tackling this!! I assume your'e still working on this? And don't worry about one or two test failures on windows, given that the windows tests up till this effor were pretty meaningless, i'm fine with them not passing 100% on windows.

**Comment by bweigel** [comment]
Yes. I am still kind of at it.

**Comment by bweigel** [comment]
Well @dschep , I guess this is it. All tests ported to tape. On windows a few fail. Quite a few are also skipped, because of missing docker and/or checks for unix file permissions. 
I don't know how those should behave under win32

Cheers!

**Comment by dschep** [comment]
Fantastic!!! Could you rebase on master to resolve the conflict?

**Comment by bweigel** [comment]
I merged master again. Seems like all the failing windows tests pass now, thanks to your recent fixes.
However, weirdly two tests fail on circleci, which didn't previously and also don't fail locally on my computer.

**Comment by dschep** [comment]
i'll take a look at those failing tests tomorrow

**Comment by bweigel** [comment]
I guess it must have been some kind of glitch with `.egg-info`-folders, which sometimes were packaged and sometimes not. This made the test kinda flaky. I just adjusted the tests to use the `__main__.py` for custom slim patterns. And this did the trick. Should be ready now :)

**Pull request merged**
